# set default task and default training config based on task
defaults:
  - task: TiagoDualWBExample
  - train: ${task}SAC
  - hydra/job_logging: disabled

# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: 1
# enable/disable headless mode and rendering (in pygame window)
headless: False
render: False

# seed - set to -1 to choose random seed
seed: -1
# set to True for deterministic performance
torch_deterministic: False
# Use the isaac sim configuration from file
sim_app_cfg_path: "/isaac_app_configs/omni.isaac.sim.python_minimal.kit"
# set the maximum number of learning iterations to train for. overrides default per-environment setting
# max_iterations: 500

## Device config
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'cpu' # 'gpu'
# whether to use cpu or gpu physx
sim_device: 'cpu' # 'gpu'
# used for gpu pipeline only - device id for running sim and task
device_id: 0
# device to run RL
rl_device: 'cuda:0' #'cpu' # 'cuda:0'

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs

#  RL Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# used to set checkpoint path
checkpoint: '' 
# checkpoint:  '/home/gino79445/Desktop/rlmmbp/learned_robot_placement/logs/TiagoDualReaching/TiagoDualReachingBHyRL/2022-11-11-15-42-48/2022-11-11-17-28-13/agent-212.msh'
# checkpoint:  '/home/gino79445/Desktop/rlmmbp/learned_robot_placement/logs/TiagoDualMultiObjFetching/TiagoDualMultiObjFetchingBHyRL/2023-09-22-00-36-10/2023-09-22-00-36-10/agent-300.msh'
# checkpoint:  '/home/gino79445/Desktop/rlmmbp/learned_robot_placement/logs/TiagoDual3Obstacle/TiagoDual3ObstacleBHyRL/2023-09-25-02-54-07/2023-09-25-02-54-07/agent-276.msh'
# checkpoint:  '/home/gino79445/Desktop/rlmmbp/learned_robot_placement/logs/TiagoDual6Obstacle/TiagoDual6ObstacleBHyRL/2023-09-27-11-04-18/2023-09-27-11-04-18/agent-300.msh'
# checkpoint: "/home/gino79445/Desktop/Research/rlmmbp/learned_robot_placement/logs/TiagoDual9Obstacle/TiagoDual9ObstacleBHyRL/2023-10-04-01-04-24/2023-10-04-01-04-24/agent-300.msh"
# number of seeds to run (run sequentially by default)
num_seeds: 5

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .
